#!/bin/bash

# julia                          file                        SNRs maxiter L Wonly CD_group lambda betas
# L2
    # CbyC
/usr/local/julia/bin/julia $MYSTORAGE/work/julia/sca/convexexpr.jl [60] 20 1 true :column 0 [0.0001,0.001,0.003,0.005,0.008,0.01] # Wonly

/usr/local/julia/bin/julia $MYSTORAGE/work/julia/sca/convexexpr.jl [60] 20 2 true :column 0 [0.0001,0.001,0.003,0.005,0.008,0.01]
/usr/local/julia/bin/julia $MYSTORAGE/work/julia/sca/convexexpr.jl [60] 20 1 false :column 0 [0.0001,0.001,0.003,0.005,0.008,0.01]