#!/bin/bash

# julia         file                        SNRs iter L Wonly sd_grp lmda beta pwradj weighted
julia $MYSTORAGE/work/julia/sca/convexexpr.jl [10] 50 1 true :column [0] [0.1,0.3] :balance2 :none
