#!/bin/bash
# julia         file                     datasets SNRs iter lambda betas method ncrng usingFastSCA pw reg sparseinit sd_group usingConvex
julia $MYSTORAGE/work/julia/sca/scaexpr.jl [:fakecell] [60] 300 [0] [0.5,1,5,10] :cgoca [15] :normal :W1 false :whole :none
