#!/bin/bash

# julia         file                      SNRs iter Msparse L Wonly sd_grp lambda betas pwradj weighted
# cbyc, L1, Wonly
# julia $MYSTORAGE/work/julia/sca/convexexpr.jl [60] 50 [0] [5,7,10,100] :normalize :balance2 :power1

# julia         file                      SNRs iter  L Wonly sd_grp lambda betas method nclsrng usingFastSCA
julia $MYSTORAGE/work/julia/sca/scaexpr.jl [:cbclface] [20] 100 [100] [5] :sca [15] false