#!/bin/bash

# julia         file                         SNRs iter L Wonly sd_grp lambda betas
# cbyc, L2, Wonly
julia $MYSTORAGE/work/julia/sca/convexexpr.jl [\"face\"] 50 1 true :column [0] [10] :none :decimate
