#!/bin/bash

# julia                          file                        SNRs maxiter L Wonly CbyC lambda betas
# pbyp, L2, w/o non-negativity
julia $MYSTORAGE/work/julia/sca/convexexpr.jl [60] 20 2 false :pixel 0 [0.0,0.0001,0.001,0.003,0.005,0.008,0.01]
julia $MYSTORAGE/work/julia/sca/convexexpr.jl [60] 20 2 true :pixel 0 [0.0001,0.001,0.003,0.005,0.008,0.01] # Wonly
