#!/bin/bash

# julia                          file                        SNRs maxiter L Wonly CbyC lambda betas
# pbyp, L1, with non-negativity
julia $MYSTORAGE/work/julia/sca/convexexpr.jl [60] 20 1 false :pixel 0.1 [0.0,0.0001,0.001,0.003,0.005,0.008,0.01]
julia $MYSTORAGE/work/julia/sca/convexexpr.jl [60] 20 1 true :pixel 0.1 [0.0001,0.001,0.003,0.005,0.008,0.01] # Wonly
