#!/bin/bash
# export resource='select[model==Intel_Xeon_Gold6242CPU280GHz && mem>32000 && tmp>2] rusage[mem=32000, tmp=2]'
# smjuliajob -R "$resource" $MYSTORAGE/work/julia/sca/expr1
# julia         file             dir_name methods initmethod iterstrt iterstop SNR factor noc lcsvd_maxiter hals_maxiter hals_α compnmf_maxiter
export jlexec=/usr/local/julia/bin/julia
export jlfile=$MYSTORAGE/work/julia/sca/paper/runtime_all.jl
#lscpu >> $MYSTORAGE/work/julia/sca/paper/SNR/machine.txt
$jlexec $jlfile \"SNR_fast\" [\"pcb\",\"pcb_precon\",\"hals\",\"compnmf\"] 1 50 20 1 15 500 400 0.1 15000