#!/bin/bash

# julia         file                         SNRs iter L Wonly sd_grp lambda betas 
# cbyc, L2
julia $MYSTORAGE/work/julia/sca/convexexpr.jl [10] 50 1 true :column [0] [3.0,4.0] :balance2 :none
