#!/bin/bash

# julia         file                         SNRs iter L Wonly sd_grp lambda betas
# cbyc, L1
julia $MYSTORAGE/work/julia/sca/convexexpr.jl [10] 50 1 true :column [0] [0.5,0.7] :balance2 :none
