#!/bin/bash
# export resource='select[model==Intel_Xeon_Gold6242CPU280GHz && mem>32000 && tmp>2] rusage[mem=32000, tmp=2]'
# smjuliajob -R "$resource" $MYSTORAGE/work/julia/sca/expr1
# julia         file             dir_name methods initmethod iterstrt iterstop SNR factor noc lcsvd_maxiter hals_maxiter hals_α compnmf_maxiter
export jlexec=/usr/local/julia/bin/julia
export jlfile=$MYSTORAGE/work/julia/sca/paper/runtime_all.jl
#lscpu >> $MYSTORAGE/work/julia/sca/paper/SNR/machine.txt
$jlexec $jlfile \"size_fast\" [\"pcb\",\"pcb_precon\",\"hals\",\"compnmf\"] 35 50 0 10 15 150 80 0.1 900
