#!/bin/bash

# julia                          file                        SNRs maxiter L Wonly CbyC lambda betas
# L2
    # CbyC
/usr/local/julia/bin/julia $MYSTORAGE/work/julia/sca/convexexpr.jl [60] 20 2 false true 0.1 [0.0001,0.001,0.003,0.005,0.008,0.01] # WH
/usr/local/julia/bin/julia $MYSTORAGE/work/julia/sca/convexexpr.jl [60] 20 2 true true 0.1 [0.0001,0.001,0.003,0.005,0.008,0.01] # Wonly
# L2
    # aC
/usr/local/julia/bin/julia $MYSTORAGE/work/julia/sca/convexexpr.jl [60] 20 2 false false 0.1 [0.0001,0.001,0.003,0.005,0.008,0.01] # WH
/usr/local/julia/bin/julia $MYSTORAGE/work/julia/sca/convexexpr.jl [60] 20 2 true false 0.1 [0.0001,0.001,0.003,0.005,0.008,0.01] # Wonly

