#!/bin/bash
# export resource='select[model==Intel_Xeon_Gold6242CPU280GHz && mem>32000 && tmp>2] rusage[mem=32000, tmp=2]'
# smjuliajob -R "$resource" $MYSTORAGE/work/julia/sca/expr1
# julia         file             dir_name methods initmethod iterstrt iterstop SNR factor ncells lcsvd_maxiter hals_maxiter hals_α compnmf_maxiter
export jlexec=/usr/local/julia/bin/julia
export jlfile=$MYSTORAGE/work/julia/sca/paper/runtime_sgd.jl
lscpu >> $MYSTORAGE/work/julia/sca/paper/SNR/machine.txt
$jlexec $jlfile \"SGD\" [:lbfgs,:slbfgs,:sgd] 12 30 0 1 15 0 30

# export juliapath=/usr/local/julia/bin/julia
# export workpath=$MYSTORAGE/work/julia/sca
# export job_group=/kim503/job_group0
# bgadd -L 30 $job_group
# # bjgroup -s $job_group
# for iter in {1..50}; do
#     smjuliajob -g $job_group -J "nc10_$iter" $juliapath $workpath/paper/runtime_all.jl \"ncells\" $iter 0 1 10 150 true true 150 0.1 800
#     smjuliajob -g $job_group -J "nc20_$iter" $juliapath $workpath/paper/runtime_all.jl \"ncells\" $iter 0 1 20 150 true true 150 0.1 800
#     smjuliajob -g $job_group -J "nc30_$iter" $juliapath $workpath/paper/runtime_all.jl \"ncells\" $iter 0 1 30 150 true true 150 0.1 800
#     smjuliajob -g $job_group -J "nc50_$iter" $juliapath $workpath/paper/runtime_all.jl \"ncells\" $iter 0 1 50 150 true true 150 0.1 800
# done
