#!/bin/bash
# export resource='select[model==Intel_Xeon_Gold6242CPU280GHz && mem>64000 && tmp>2] rusage[mem=64000, tmp=2]'
# smjuliajob -R "$resource" $MYSTORAGE/work/julia/sca/paper/rnaseq/expr1
# julia         file             dir_name methods num_expriments SNR factor ncells lcsvd_maxiter hals_maxiter hals_α compnmf_maxiter
export jlexec=/usr/local/julia/bin/julia
export jlfile=$MYSTORAGE/work/julia/sca/paper/rnaseq/runtime_hals.jl
lscpu >> $MYSTORAGE/work/julia/sca/paper/rnaseq/hals_machine.txt
$jlexec $jlfile 1000 0.1 50
$jlexec $jlfile 1000 0.1 100
