#!/bin/bash
# export resource='select[model==Intel_Xeon_Gold6242CPU280GHz && mem>64000 && tmp>2] rusage[mem=64000, tmp=2]'
# smjuliajob -R "$resource" $MYSTORAGE/work/julia/sca/paper/rnaseq/expr1
# julia         file             dir_name methods num_expriments SNR factor ncells lcsvd_maxiter hals_maxiter hals_α compnmf_maxiter
export jlexec=/usr/local/julia/bin/julia
export jlfile=$MYSTORAGE/work/julia/sca/paper/rnaseq/runtime_lcsvd.jl
lscpu >> $MYSTORAGE/work/julia/sca/paper/rnaseq/lcsvd_machine.txt
$jlexec $jlfile 500 0. 0.005 5.0 0. 100
$jlexec $jlfile 500 0. 0.005 5.0 0. 200
