#!/bin/bash
# export resource='select[model==Intel_Xeon_Gold6242CPU280GHz && mem>4000 && tmp>2] rusage[mem=4000, tmp=2]'
# smjuliajob -R "$resource" $MYSTORAGE/work/julia/sca/paper/rnaseq/expr1
# julia         file             dir_name methods num_expriments SNR factor ncells lcsvd_maxiter hals_maxiter hals_α compnmf_maxiter
export jlexec=/usr/local/julia/bin/julia
export jlfile=$MYSTORAGE/work/julia/sca/paper/rnaseq/runtime_small_hals_noc.jl
$jlexec $jlfile 5 2000 [300,400,500,600,700,800,900,1000]


